/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChooseRouteImport } from './routes/choose'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanReadyRouteImport } from './routes/plan.ready'
import { Route as PlanProfileRouteImport } from './routes/plan.profile'
import { Route as PlanAuthRouteImport } from './routes/plan.auth'
import { Route as AuthenticatedStartRouteImport } from './routes/_authenticated/start'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedItineraryRouteImport } from './routes/_authenticated/itinerary'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPlacePhotoRouteImport } from './routes/api/public/place-photo'

const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoute = ChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanReadyRoute = PlanReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => PlanRoute,
} as any)
const PlanProfileRoute = PlanProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PlanRoute,
} as any)
const PlanAuthRoute = PlanAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PlanRoute,
} as any)
const AuthenticatedStartRoute = AuthenticatedStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItineraryRoute = AuthenticatedItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPlacePhotoRoute = ApiPublicPlacePhotoRouteImport.update({
  id: '/api/public/place-photo',
  path: '/api/public/place-photo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose': typeof ChooseRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/itinerary': typeof AuthenticatedItineraryRoute
  '/map': typeof AuthenticatedMapRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/start': typeof AuthenticatedStartRoute
  '/plan/auth': typeof PlanAuthRoute
  '/plan/profile': typeof PlanProfileRoute
  '/plan/ready': typeof PlanReadyRoute
  '/api/public/place-photo': typeof ApiPublicPlacePhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose': typeof ChooseRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/itinerary': typeof AuthenticatedItineraryRoute
  '/map': typeof AuthenticatedMapRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/start': typeof AuthenticatedStartRoute
  '/plan/auth': typeof PlanAuthRoute
  '/plan/profile': typeof PlanProfileRoute
  '/plan/ready': typeof PlanReadyRoute
  '/api/public/place-photo': typeof ApiPublicPlacePhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/choose': typeof ChooseRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/itinerary': typeof AuthenticatedItineraryRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/start': typeof AuthenticatedStartRoute
  '/plan/auth': typeof PlanAuthRoute
  '/plan/profile': typeof PlanProfileRoute
  '/plan/ready': typeof PlanReadyRoute
  '/api/public/place-photo': typeof ApiPublicPlacePhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose'
    | '/login'
    | '/plan'
    | '/admin'
    | '/agenda'
    | '/chat'
    | '/dashboard'
    | '/discover'
    | '/itinerary'
    | '/map'
    | '/saved'
    | '/start'
    | '/plan/auth'
    | '/plan/profile'
    | '/plan/ready'
    | '/api/public/place-photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose'
    | '/login'
    | '/plan'
    | '/admin'
    | '/agenda'
    | '/chat'
    | '/dashboard'
    | '/discover'
    | '/itinerary'
    | '/map'
    | '/saved'
    | '/start'
    | '/plan/auth'
    | '/plan/profile'
    | '/plan/ready'
    | '/api/public/place-photo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/choose'
    | '/login'
    | '/plan'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/discover'
    | '/_authenticated/itinerary'
    | '/_authenticated/map'
    | '/_authenticated/saved'
    | '/_authenticated/start'
    | '/plan/auth'
    | '/plan/profile'
    | '/plan/ready'
    | '/api/public/place-photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChooseRoute: typeof ChooseRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRouteWithChildren
  ApiPublicPlacePhotoRoute: typeof ApiPublicPlacePhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose': {
      id: '/choose'
      path: '/choose'
      fullPath: '/choose'
      preLoaderRoute: typeof ChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/ready': {
      id: '/plan/ready'
      path: '/ready'
      fullPath: '/plan/ready'
      preLoaderRoute: typeof PlanReadyRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/profile': {
      id: '/plan/profile'
      path: '/profile'
      fullPath: '/plan/profile'
      preLoaderRoute: typeof PlanProfileRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/auth': {
      id: '/plan/auth'
      path: '/auth'
      fullPath: '/plan/auth'
      preLoaderRoute: typeof PlanAuthRouteImport
      parentRoute: typeof PlanRoute
    }
    '/_authenticated/start': {
      id: '/_authenticated/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AuthenticatedStartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/itinerary': {
      id: '/_authenticated/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof AuthenticatedItineraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/place-photo': {
      id: '/api/public/place-photo'
      path: '/api/public/place-photo'
      fullPath: '/api/public/place-photo'
      preLoaderRoute: typeof ApiPublicPlacePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedItineraryRoute: typeof AuthenticatedItineraryRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedStartRoute: typeof AuthenticatedStartRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedItineraryRoute: AuthenticatedItineraryRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedStartRoute: AuthenticatedStartRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PlanRouteChildren {
  PlanAuthRoute: typeof PlanAuthRoute
  PlanProfileRoute: typeof PlanProfileRoute
  PlanReadyRoute: typeof PlanReadyRoute
}

const PlanRouteChildren: PlanRouteChildren = {
  PlanAuthRoute: PlanAuthRoute,
  PlanProfileRoute: PlanProfileRoute,
  PlanReadyRoute: PlanReadyRoute,
}

const PlanRouteWithChildren = PlanRoute._addFileChildren(PlanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChooseRoute: ChooseRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRouteWithChildren,
  ApiPublicPlacePhotoRoute: ApiPublicPlacePhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
